site_name: Kurt Jacobson
site_description: Kurt Jacobson's personal site
site_url: https://kurtjacobson.github.io

repo_name: KurtJacobson/site
repo_url: https://github.com/KurtJacobson/site/

remote_branch: master
remote_name: https://github.com/KurtJacobson/kurtjacobson.github.io.git

# Build to master branch of kurtjacobson.github.io
site_dir: /home/kurt/Sources/kurtjacobson.github.io

theme: material
site_favicon: 'images/favicon.ico'

pages:
- Home: index.md
- Machine Shop:
  - CNC Conversions: 
    - RF45 Mill: RF45.md
- Python Examples: python/python_examples.md

markdown_extensions:
  - admonition
  - codehilite(linenums=true)

extra:
  logo: 'images/kcj.png'
  palette:
    primary: 'gray'
    accent: 'indigo'
